defaults:
  - local: ../../hpack-common.yaml
  - local: ../../hpack-relude.yaml

name: tail
version: 0.1.0.0
license: MIT
copyright: 2025 Sridhar Ratnakumar
maintainer: srid@srid.ca
author: Sridhar Ratnakumar
category: System
homepage: https://github.com/juspay/vira/tree/main/packages/tail
synopsis: Haskell API for tail -f streaming
description: A Haskell library providing an API for tail -f style file streaming using STM, process, and async.

dependencies:
  - async
  - stm
  - text
  - typed-process
  - which
  - filepath
  - directory
  - stm-chans

library:
  source-dirs: src

data-files:
  - test-fixture.txt

executables:
  tail-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tail
      - hspec
      - hspec-discover
      - temporary
      - directory
