defaults:
  - local: ../../hpack-common.yaml
  - local: ../../hpack-relude.yaml

name: bb
version: 0.1.0.0
license: MIT
copyright: 2025 Juspay
maintainer: srid@srid.ca
author: Sridhar Ratnakumar
category: System
synopsis: Bitbucket API bindings and CLI tool
description: Library for Bitbucket REST API operations with command-line interface
homepage: https://github.com/juspay/vira/tree/main/packages/bb
extra-source-files:
  - CHANGELOG.md

dependencies:
  - aeson
  - bytestring
  - co-log
  - co-log-effectful
  - co-log-effectful-simple
  - directory
  - effectful
  - effectful-core
  - filepath
  - git-effectful
  - modern-uri
  - optparse-applicative
  - process
  - req
  - text

library:
  source-dirs: src

executables:
  bb:
    main: Main.hs
    source-dirs: app
    dependencies:
      - bb
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  bb-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - bb
      - hspec
      - hspec-discover
