#!/bin/sh

# For use with GHC home units
# https://x.com/sridca/status/1901283945779544362

exec cabal repl "$@" \
    vira vira-repo-config vira-types attic-hs tail warp-tls-simple htmx-lucid-contrib git-effectful gh-signoff
