#!/bin/sh

# For use with GHC home units
# https://x.com/sridca/status/1901283945779544362

exec cabal repl "$@" \
    vira vira-ci-types acid-state-events attic bb cachix tail htmx-lucid-contrib git-effectful co-log-effectful-simple gh nix nix-cache-server devour-flake
