defaults:
  - local: ../../hpack-common.yaml
  - local: ../../hpack-relude.yaml

name: github-app-auth
version: 0.1.0.0
license: MIT
copyright: 2024 Juspay
maintainer: me@shivaraj-bh.in
author: Shivaraj B H
category: Web
synopsis: GitHub App authentication
description: |
  Authenticate as a GitHub App installation.
  Creates JWTs and exchanges them for installation access tokens.

dependencies:
  - bytestring
  - github
  - jose
  - lens
  - text
  - time
  - crypton
  - crypton-x509
  - crypton-x509-store

library:
  source-dirs: src
