defaults:
  - local: ../../hpack-common.yaml
  - local: ../../hpack-relude.yaml

name: bitbucket-cli
version: 0.1.0.0
license: MIT
copyright: 2025 Juspay
maintainer: srid@srid.ca
author: Sridhar Ratnakumar
category: System
synopsis: Command-line tool for Bitbucket API
description: A CLI tool for interacting with Bitbucket Server
homepage: https://github.com/juspay/vira/tree/main/packages/bitbucket-cli

dependencies:
  - bitbucket

executables:
  bb:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
