defaults:
  - local: ../../hpack-common.yaml
  - local: ../../hpack-relude.yaml

name: stm-circular-buffer
version: 0.1.0.0
license: MIT
copyright: 2026 Sridhar Ratnakumar
maintainer: srid@srid.ca
author: Sridhar Ratnakumar
category: Concurrency
homepage: https://github.com/juspay/vira/tree/main/packages/stm-circular-buffer
synopsis: Circular buffer with drop-oldest semantics using STM
description: |
  A circular buffer implementation using STM TBMQueue with drop-oldest semantics.
  When the buffer is full, adding new items causes the oldest items to be dropped.

dependencies:
  - stm
  - stm-chans

library:
  source-dirs: src

tests:
  stm-circular-buffer-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - stm-circular-buffer
      - hspec
