defaults:
  - local: ../../hpack-common.yaml
  - local: ../../hpack-relude.yaml

name: git-effectful
version: 0.1.0.0
license: AGPL-3.0-or-later
copyright: 2025 Juspay
maintainer: srid@srid.ca
author: Sridhar Ratnakumar
category: Git
synopsis: Git operations using effectful
description: A standalone library for git operations using the effectful library

ghc-options:
  - -fplugin=Effectful.Plugin

dependencies:
  - aeson
  - co-log
  - co-log-core
  - co-log-effectful
  - co-log-effectful-simple
  - containers
  - directory
  - effectful
  - effectful-core
  - effectful-plugin
  - filepath
  - http-api-data
  - ixset-typed
  - lens
  - lukko
  - megaparsec
  - modern-uri
  - process
  - safecopy
  - servant-server
  - text
  - time
  - unliftio
  - which

library:
  source-dirs: src

executables:
  git-effectful-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - git-effectful
      - hspec
      - hspec-discover
      - temporary
      - process
      - filepath
