defaults:
  - local: ../../hpack-common.yaml
  - local: ../../hpack-relude.yaml

name: logsink
version: 0.1.0.0
license: MIT
copyright: 2025 Sridhar Ratnakumar
maintainer: srid@srid.ca
author: Sridhar Ratnakumar
category: Concurrency
homepage: https://github.com/juspay/vira/tree/main/packages/logsink
synopsis: Unified log sink with pub/sub streaming
description: |
  A Haskell library providing a unified sink abstraction for concurrent
  log writing with pub/sub streaming via STM-based broadcast channels.

dependencies:
  - async
  - stm
  - text
  - stm-chans
  - tail

library:
  source-dirs: src
  dependencies:
    - aeson

executables:
  logsink-example:
    main: Main.hs
    source-dirs: example
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - logsink
      - aeson
      - process

tests:
  logsink-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - logsink
      - hspec
      - async
