defaults:
  - local: ../../hpack-common.yaml
  - local: ../../hpack-relude.yaml

name: vira-ci-types
version: 0.1.0.0
license: AGPL-3.0-or-later
copyright: 2024 Juspay
maintainer: srid@srid.ca
author: Sridhar Ratnakumar
category: Web
homepage: https://github.com/juspay/vira
synopsis: Vira CI-specific types
description: CI-specific types and data structures for vira, separated for use in hint configuration

dependencies:
  - aeson
  - attic
  - base16-bytestring
  - bytestring
  - containers
  - data-default
  - deriving-aeson
  - effectful
  - effectful-core
  - filepath
  - git-effectful
  - http-api-data
  - ixset-typed
  - optics-core
  - optics-th
  - safecopy
  - servant
  - text
  - time
  - record-hasfield

library:
  source-dirs: src
