defaults:
  - local: ../../hpack-common.yaml
  - local: ../../hpack-relude.yaml

name: tabler-icons
version: 0.1.0.0
license: MIT
copyright: 2024 Sridhar Ratnakumar
maintainer: srid@srid.ca
author: Sridhar Ratnakumar
category: Web
synopsis: Haskell bindings for Tabler SVG icons
description: |
  Haskell bindings for the Tabler icons library.
  
  This package provides access to Tabler SVG icons as ByteString values,
  allowing them to be embedded directly in Haskell web applications.
  
  The icons are sourced from https://github.com/tabler/tabler-icons

dependencies:
  - bytestring

library:
  source-dirs: src
  exposed-modules:
    - Web.TablerIcons.Outline
    - Web.TablerIcons.Filled