defaults:
  - local: ../../hpack-common.yaml
  - local: ../../hpack-relude.yaml

name: vira
version: 0.1.0.0
license: AGPL-3.0-or-later
copyright: 2024 Juspay
maintainer: srid@srid.ca
author: Sridhar Ratnakumar
category: Web
homepage: https://github.com/juspay/vira
synopsis: Nix CI & Cache
description: vira - Nix CI & Cache

data-dir: static
data-files:
  - js/htmx-ext-debug.js
  - js/htmx-extensions/src/sse/sse.js
  - js/htmx.min.js
  - js/hyperscript.min.js
  - tailwind.css
  - vira-logo.svg
  - vira-logo-apple.svg
  - vira-logo-penguin.svg

ghc-options:
  - -fplugin=Effectful.Plugin

dependencies:
  - acid-state
  - aeson
  - async
  - base16-bytestring
  - bytestring
  - cereal
  - tabler-icons
  - co-log
  - co-log-core
  - co-log-effectful
  - containers
  - dani-servant-lucid2
  - data-default
  - deriving-aeson
  - directory
  - effectful
  - effectful-core
  - effectful-plugin
  - http-media
  - effectful-th
  - envparse
  - filepath
  - gh-signoff
  - git-effectful
  - gitlib
  - hostname
  - hspec
  - hspec-discover
  - htmx
  - which
  - htmx-lucid
  - htmx-lucid-contrib
  - htmx-servant
  - http-api-data
  - http-types
  - ixset-typed
  - lucid2
  - mtl
  - optics-core
  - optics-th
  - optparse-applicative
  - process
  - profunctors
  - QuickCheck
  - safecopy
  - servant
  - servant-event-stream
  - servant-server
  - shower
  - sqlite-simple
  - stm
  - streaming
  - tail
  - text
  - time
  - wai
  - wai-extra
  - wai-middleware-static
  - warp
  - warp-tls-simple
  - with-utf8
  - binary

library:
  source-dirs: src

executables:
  vira:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - vira

tests:
  vira-tests:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - vira
