defaults:
  - local: ../../hpack-common.yaml
  - local: ../../hpack-relude.yaml

name: vira
version: 0.1.0.0
license: AGPL-3.0-or-later
copyright: 2024 Juspay
maintainer: srid@srid.ca
author: Sridhar Ratnakumar
category: Web
homepage: https://github.com/juspay/vira
synopsis: No-frills CI for small teams using Nix
description: No-frills CI for small teams using Nix

data-dir: static
data-files:
  - js/htmx-ext-debug.js
  - js/htmx-extensions/src/sse/sse.js
  - js/htmx.min.js
  - js/hyperscript.min.js
  - tailwind.css
  - vira-logo.svg
  - vira-logo-apple.svg
  - vira-logo-penguin.svg
  - test/sample-configs/simple-example.hs

ghc-options:
  - -fplugin=Effectful.Plugin

dependencies:
  - acid-state
  - aeson
  - ansi-terminal
  - async
  - attic
  - cachix
  - base16-bytestring
  - bytestring
  - cereal
  - tabler-icons
  - co-log >= 0.7
  - co-log-core
  - co-log-effectful
  - co-log-effectful-simple
  - containers
  - dani-servant-lucid2
  - dependent-map
  - dependent-sum
  - data-default
  - deriving-aeson
  - aeson-pretty
  - devour-flake
  - directory
  - effectful
  - effectful-core
  - effectful-plugin
  - http-media
  - effectful-th
  - envparse
  - filepath
  - filepattern
  - gh
  - git-effectful
  - hostname
  - hint
  - hspec
  - hspec-discover
  - htmx
  - which
  - htmx-lucid
  - htmx-lucid-contrib
  - htmx-servant
  - http-api-data
  - http-types
  - ixset-typed
  - lucid2
  - modern-uri
  - mtl
  - nix
  - nix-serve-ng
  - optics-core
  - optics-th
  - optparse-applicative
  - process
  - profunctors
  - QuickCheck
  - record-hasfield
  - safecopy
  - servant
  - servant-event-stream
  - servant-server
  - shower
  - sqlite-simple
  - stm
  - streaming
  - tail
  - text
  - time
  - toml-reader
  - unliftio
  - vira-ci-types
  - hint-nix
  - wai
  - wai-extra
  - wai-middleware-static
  - warp
  - warp-tls-simple
  - with-utf8
  - binary

library:
  source-dirs: src

executables:
  vira:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - vira
  vira-tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - vira
