defaults:
  - local: ../../hpack-common.yaml
  - local: ../../hpack-relude.yaml

name: attic
version: 0.1.0.0
license: MIT
copyright: 2025 Juspay
maintainer: srid@srid.ca
author: Sridhar Ratnakumar
category: System
homepage: https://github.com/juspay/vira
synopsis: Haskell bindings for Nix attic cache
description: Haskell types and functions for working with NIx attic cache servers

extra-source-files:
  - CHANGELOG.md

dependencies:
  - aeson
  - directory
  - http-api-data
  - megaparsec
  - modern-uri
  - process
  - safecopy
  - servant
  - template-haskell
  - text
  - toml-reader
  - which

library:
  source-dirs: src

tests:
  attic-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - attic
      - hspec
      - hspec-discover
