name: "Website"
on:
  push:
    branches:
      - main
      - docs

jobs:
  build:
    runs-on: x86_64-linux
    steps:
      - uses: actions/checkout@v4
      - name: Build the website (Nix) 🔧
        run: |
          cd ./docs && nix build -o ../_site
      # Cloudflare will then deploy the gh-pages branch via Pages.
      - name: Push to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site/
